### ISSUE TITLE
dist/ is not updated to v0.0.2

### ISSUE THREAD

**Issue by vzvu3k6k** [increments/tasklist.js#1]
src/tasklist.js is updated at 228b736959896d5a0bde3eabe49ed972588db7a0, but dist/tasklist(.min).js are not updated.

**Comment by r7kamura** [comment]
oops, I'll update it soon

**Comment by r7kamura** [comment]
Released v0.0.3. Thanks for your report :+1: 
[Release v0.0.3 · increments/tasklist.js](https://github.com/increments/tasklist.js/releases/tag/v0.0.3)
